### ISSUE TITLE
Styles don't apply to compound variant descendants

### ISSUE THREAD

**Issue by mattaningram** [gluestack/gluestack-style#489] opened 2023-10-18 22:43 UTC
I am attempting to customize the styles of a `Button` component setup with `ButtonText`. Styling with variants and compound variants works fine for default state styling of the descendants, and I can style the root element in `:hover` and `:active` states. But styles applied to descendants when the parent component is in a different state don't work.

Am I doing something wrong or is this a bug?

**Text does change color on hover**
```typescript
variant: {
  solid: {
    _text: {
      color: 'white',
    },
    ':hover': {
      _text: {
        color: '$gray2'
      },
    },
  },
},
```

**Text does not change color on hover**
```typescript
compoundVariants: [
{
  variant: 'solid',
  color: 'primary',
  value: {
    _text: {
      color: '$primary0',
    },
    ':hover': {
      _text: {
        color: '$primary1'
      },
    },
  },
},
]
```

**Comment by ankit-tailor** [comment] 2023-10-19 13:22
Hey @mattaningram, Thanks for reporting the issue. I'll look into it.

**Comment by ankit-tailor** [comment] 2023-11-08 09:05
The issue is fixed in the latest version. Let me know if it works for you.

**Closed by ankit-tailor** 2023-11-08 09:05 UTC
