### ISSUE TITLE
styled text components with different styling causes invalid overrides

### ISSUE THREAD

**Issue by alidcast** [gluestack/gluestack-style#132] opened 2023-04-17 22:00 UTC
With one styled text component, output is correct:
```
export const Heading = styled(
  Text,
  {fontFamily: "Family1", fontWeight: "900",fontStyle: "normal"},
)


// generated css
[data-style~="yq94gz-192hlel"] {
    font-family: Family1;
    font-style: normal;
    font-weight: 900;
}
```

With two styled text component, the output is incorrectly overriden by subsequent component:

```
export const Heading = styled(
  Text,
  {fontFamily: "Family1", fontWeight: "900",fontStyle: "normal"},
)

export const Paragraph = styled(
  Text,
  {fontFamily: "Family2", fontWeight: "400",fontStyle: "normal"},
)


// generated css
[data-style~="1d2gamg-1uvcg3y"] {
    font-family: Family1;
    font-style: normal;
    font-weight: 400;
}
[data-style~="ew2hsx-o7vmdi"] {
    font-family: Family1;
    font-style: normal;
    font-weight: 900;
}
```

**Comment by rayan1810** [comment] 2023-04-20 05:52
Hey @alidcast can you share the code, like how you are using the styled component.

**Comment by ankit-tailor** [comment] 2023-06-12 06:23
Hey @alidcast! The issue is fixed. Please update to the latest version of `@gluestack-style/react`. Closing the issue for now, Feel free to re-open it if you still face the issue.

**Closed by ankit-tailor** 2023-06-12 06:23 UTC
